### ISSUE TITLE
Unicode filenames cause Listen 2.7.9 to crash with Jekyll

### ISSUE THREAD

**Issue by dlo** [guard/listen#250]
When I make a change in Jekyll to a file, I get the following exception from listen. No files are updated after any change to a file in my blog (this worked in the previous version of Jekyll—not sure which listen version that was associated with).

Thanks! Let me know if there's anything else I can provide to help. The source code for my blog is available at https://github.com/dlo/dlo.github.com if you'd like to try to reproduce this on your end.

```
$ jekyll serve -w
Configuration file: /Users/dan/Documents/Projects/dlo.github.com/_config.yml
            Source: /Users/dan/Documents/Projects/dlo.github.com
       Destination: ./_site
      Generating...

  Populating LSI...
Rebuilding index...
                         Build Warning: Layout 'nil' requested in atom.xml does not exist.
     Build Warning: Layout 'nil' requested in rss.xml does not exist.
                    done.
 Auto-regeneration: enabled for '/Users/dan/Documents/Projects/dlo.github.com'
Configuration file: /Users/dan/Documents/Projects/dlo.github.com/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
E, [2014-08-25T08:37:03.647681 #4309] ERROR -- : Listen::Change crashed!
Encoding::CompatibilityError: inspected result must be ASCII only or use the same encoding with default external
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/set.rb:474:in `inspect'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/set.rb:474:in `inspect'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/listen-2.7.9/lib/listen/directory.rb:21:in `scan'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/listen-2.7.9/lib/listen/change.rb:38:in `change'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
E, [2014-08-25T08:37:03.767992 #4309] ERROR -- : Listen::Change crashed!
Encoding::CompatibilityError: inspected result must be ASCII only or use the same encoding with default external
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/set.rb:474:in `inspect'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/set.rb:474:in `inspect'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/listen-2.7.9/lib/listen/directory.rb:21:in `scan'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/listen-2.7.9/lib/listen/change.rb:38:in `change'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
	/Users/dan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

**Comment by rschiang** [comment]
Update: The same issue triggers on [listener.rb line 335](https://github.com/guard/listen/blob/master/lib/listen/listener.rb#L335), where `inspect` explodes enormously.

**Comment by e2** [comment]
@rschiang - inspect shouldn't explode if you have utf-8 only characters. Otherwise, you probably have this bug: https://github.com/guard/listen/issues/238 - if so, give me a few details about the error and filenames used, etc.

If you just want to avoid the inspect error, you can try: https://github.com/guard/listen/pull/291

with this in your Gemfile:
```ruby
gem 'guard', github: 'guard/guard', branch: 'avoid_calling_debug_log_code'
```

**Comment by rschiang** [comment]
Here's line 335:
```
      _debug "raw queue: #{[type, dir, rel_path, options].inspect}"
```

Here's the error message:

```
ERROR -- : run() in thread failed: inspected result must be ASCII only or use the same encoding with default external: ~/.rvm/gems/ruby-2.0.0-p247/gems/listen-2.8.4/lib/listen/listener.rb:336:in `inspect'
```

A quick investigation narrows down problem to `dir.inspect`. Simply `print dir.inspect` would cause the same crash if file path has Unicode in it (or could be dereferenced to Unicode file path.)

Strange things here is that OS X returns UTF-8 by default, so there must be something wrong with the encodings (?)

**Comment by e2** [comment]
@rschiang - I'd need a bit more information than that.

Try to add the following code:
```ruby
_debug "internal encoding: #{Encoding.default_internal.inspect}"
_debug "external encoding: #{Encoding.default_external.inspect}"
_debug "dir encoding: #{dir.encoding.inspect}"
_debug "rel_path encoding: #{rel_path.encoding.inspect}"
_debug "string encoding: #{"foo".encoding.inspect}"
_debug "FS encoding: #{Pathname(dir).children.first.to_s.encoding}"
_debug "writing string to dir_value.bin..."
IO.binwrite("dir_value.bin", dir)
_debug "writing watched directories value ..."
IO.binwrite("watchdirs_value.bin", @directories.inspect)
```

And put the generated files into a gists, so I can e.g. turn them into unit tests.

Thanks!

**Comment by rschiang** [comment]
Gist [here](https://gist.github.com/rschiang/7e1fc9ee98266cf6ed30).

---

The `dir` variable is actually a `Pathname` according to console, 

    E, [2015-01-07T21:38:37.316272 #86972] ERROR -- : run() in thread failed: undefined method `encoding' for #<Pathname:0x007fd26b084040>:~/.rvm/gems/ruby-2.0.0-p247/gems/listen-2.8.4/lib/listen/listener.rb:337:in `_queue_raw_change'

`@directories.inspect` does not work, either:

    E, [2015-01-08T16:20:49.437466 #87945] ERROR -- : run() in thread failed: inspected result must be ASCII only or use the same encoding with default external:~/.rvm/gems/ruby-2.0.0-p247/gems/listen-2.8.4/lib/listen/listener.rb:345:in `inspect'

Should have directly send PRs instead, but I'm not so familar with Ruby libs :( eventually I just commented out all failing codes.

**Comment by e2** [comment]
> @directories.inspect does not work, either

That seems like the problem. Could you try this instead (instead of the `@directories.inspect`):

```ruby
begin
  _debug "raw queue: #{[type, dir, rel_path, options].inspect}
rescue Exception
  IO.binwrite("failing_dir_value.bin", dir)
  @directories.each_with_index { |obj, idx| IO.binwrite("watchdirs_value.#{idx}.bin", obj)}
  abort
end
```

Also, how are you setting the directories parameter to Listen? Is it in a Ruby file "encoding magic"? Are you using Jekyll? If so, could you add your `_config.yml` (I just want to know the encoding of the 'source' option, which is passed to guard - this could be a Jekyll bug).

**Comment by nhoizey** [comment]
I use Jekyll and also have this issue. I don't know Ruby.

What can I do to help?

**Comment by e2** [comment]
@nhoizey - upgrade your listen version (`bundle update listen` if you're using bundler). You shouldn't have the issue in later versions of Listen (e.g. 2.10.0). 

If you still do, create a small repository where the error occurs and publish it on github, so I can download it and work something out.

**Comment by nhoizey** [comment]
listen updated, it seems I don't have the issue anymore, thanks!

**Comment by e2** [comment]
@nhoizey - glad to help. You may get the issue if you turn on debugging in Listen (it crashes when Listen creates the debugging messages). 

Just curious - what filename did you have and in what encoding? Do you use ISO-8859-1 characters?

**Comment by nhoizey** [comment]
I use french characters with accents, like "vidéo".
