### ISSUE TITLE
Support a "relative" option (e.g. '-r') to report changes relative to current dir

### ISSUE THREAD

**Issue by e2** [guard/listen#297]
This would solve this problem on VMs: https://github.com/guard/guard/issues/751

Currently, TCP sends full paths, e.g. `/home/user/project/foo`, which makes no sense for TCP broadcasting if that exact path doesn't exist on another machine.

Ideally, TCP broadcaster should always send paths relative to current directory, unless custom directories are given with the '-d' option.

**Comment by jschroeder9000** [comment]
Thanks for looking at this. :+1:
