### ISSUE TITLE
High CPU usage on OSX with Jekyll and Sass

### ISSUE THREAD

**Issue by e2** [guard/listen#310]
Originally reported here: https://github.com/jekyll/jekyll/issues/2570 , but opened as a new issue in case it's a Listen bug.

Gist is here: https://gist.github.com/lilchen/31d09272fc410256fb2a

Initial diagnosis/problem: 

- large project (lots of watched dirs)
- and OSX adapter is not scanning changes fast enough
- may be unnecessarily doing full recursion instead of checking just subdirs
- multiple fsevents happening quickly (?)
```
D, [2015-05-29T22:58:22.024879 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site
D, [2015-05-29T22:58:22.537417 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/bfa-exhibition
D, [2015-05-29T22:58:22.544399 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/ted-talks-extra-bar
D, [2015-05-29T22:58:22.563488 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/growing-up-in-smash-as-a-girl
D, [2015-05-29T22:58:22.565682 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/why-awareness-in-smash-is-vital
D, [2015-05-29T22:58:22.566468 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/insight-into-stream-overlay
D, [2015-05-29T22:58:22.690295 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/insight-into-stream-overlay
D, [2015-05-29T22:58:22.692338 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/advice-to-younger-designers
D, [2015-05-29T22:58:22.692682 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/post-empathy-talk-reflections
D, [2015-05-29T22:58:22.692793 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/ted-quotes
D, [2015-05-29T22:58:22.692897 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/tea-party-series
D, [2015-05-29T22:58:22.692999 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/the-new-meta
D, [2015-05-29T22:58:22.693120 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/animated-swiss-poster
D, [2015-05-29T22:58:22.693243 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/ted-holiday-card
D, [2015-05-29T22:58:22.693358 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work/crossfit-hartford
D, [2015-05-29T22:58:22.693460 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/gaming
D, [2015-05-29T22:58:22.693562 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog/design
D, [2015-05-29T22:58:22.693665 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/blog
D, [2015-05-29T22:58:22.693765 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/about
D, [2015-05-29T22:58:22.693863 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site
D, [2015-05-29T22:58:22.693958 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site/_site/work
D, [2015-05-29T22:58:26.039616 #15492] DEBUG -- : fsevent: /Users/lilchen/design/web/lilchen-site
```

**Comment by e2** [comment]
@lilchen - there's a patch for fixing the recursion problem (not tested well enough to release). 

Could you try it?

1. use this in your Gemfile: 
```ruby
gem 'listen', github: 'guard/listen', branch: 'e2-rework_record_logic'
```
2. `bundle update listen`
3. `bundle exec guard`

That should reduce the work Listen does quite a bit - but there's a small risk Listen may not catch some changes (let me know if that ever occurs).

**Comment by lilchen** [comment]
@e2 Just followed the steps above, [this](https://gist.github.com/lilchen/829b7c46adbfb372197b) is what Terminal spits out when I serve Jekyll again.

I can't shake the feeling that something tiny within my site structure is causing this. Gonna make a repo for this.

**Comment by e2** [comment]
I've made changes meanwhile, so

1. in your `Gemfile`: 
```ruby
gem 'listen', github: 'guard/listen', branch: 'e2-rework_record_logic', ref: '120f26d'
```
2. Run `bundle update listen`
3. `LISTEN_GEM_FSEVENT_NO_RECURSION=1 LISTEN_GEM_DEBUGGING=2 bundle exec jekyll serve` (yes, the above instructions were obviously wrong here)

You should see a message on startup: `WARNING: Recursive scanning is disabled`

Sorry about the trouble on OSX (blame Apple?) - maybe I should start a kickstarter so I can buy myself a macbook and some time to properly implement OSX support (I don't use OSX).

If this doesn't work out and you're in a hurry to make things snappy enough, I'd suggest a virtual machine with Linux (e.g. by using Vagrant), copy the files there (and setup a way to access the files from the host), run jekyll there, forward the port so you can browse locally, etc.

(This will help you completely side-step at least 3 known "slow areas" in OSX).

Some details:

- You have only 1 fsevent (which is good), so something is screwed up on the Listen side.
- You can probably ignore the `assets/_sass/.sass-cache` directory and `assets/_sass/vendor` directory
- Make sure you don't have any big files there
- You can ignore extensions you're not working with, e.g. fonts (ttf, svg, woff), images (jpg)

There are other things we can try here. Ideally, you could setup the project so that files you "work with" are in a single directory - and watch just that directory (symlinks can help). If you setup a repo large enough, I might figure out something decent.

Anyway - first try the above with the Gemfile (should help), try and ignore more files/dirs and slightly change the structure of the project (so files you don't want to watch aren't in the subdirectories of the files you want to watch).

I have quite a bit of ideas to make things really snappy (and/or find the problem), but I don't want to overwhelm you.

After we improve things, I want to make an OSX-specific wiki with tips for large projects like yours (it's the least I can do at this point).

**Comment by lilchen** [comment]
@e2 Whoa, I had no idea you were advising me as a non-OSX user. Thank you! I updated everything and my terminal now looks like [this](https://gist.github.com/lilchen/e1e5cf300078291b6a12).

I'll try to ignore as much as I can, but from what I've noticed, when I ignore scripts/fonts/etc, things start breaking. For instance, I ignored my scroll-to-top-button script and it stopped working when I previewed my site locally.

Thanks again! I s'pose this will have to do, so much better than seeing my activity jump to 104% and hearing my fans go crazy.

**Comment by e2** [comment]
@lilchen - I've sent a PR with a "better" directory structure. Let me know if it helps (it should!).

The default Jekyll structure (with files in the root directory and a _site dir) isn't any good for watching (especially on OSX).

There's still a performance problem on OSX that needs work, but that's going to take time.

Thanks for putting up the repo - I'll use it for performance testing (it's a good example).

**Comment by lilchen** [comment]
@e2 Thank you so much >_<! You know, I totally had it split into src vs _site, but whenever I tried, I got this [error](https://github.com/jekyll/jekyll/issues/3491) on certain pages. I'll fuss around with configuration a bit more, especially with your advice you provided. Thanks a million!

**Comment by e2** [comment]
@lilchen - I had the same error before I moved the `_data` directory to source - this setup works now on all changes (I've updated the PR or you can clone https://github.com/e2/lilchen.com.git to try it out).

I've checked other projects (grunt, gaze, zeus) - and most of them stumble/workaround all kinds of OSX problems in one way or another, while I can't even try anything out without having OSX myself (on Linux, changes are reported instantly, even with tens of thousands of files - because watching is build into the OS).

I think I can *safely* speed up Listen on OSX (the key word is "safely") - but I have to first simulate OSX problems on my setup (tough).

Anyway, I do wish designers could spend more time designing - instead of fighting with tools and configurations.

**Comment by lilchen** [comment]
@e2 I just did all of your fixes! IT'S WORKING. I did leave out changing 2x to x2 though, I wasn't sure what that revision was meant for!

Regardless, thank you SO MUCH. I'm new to Git and every time I see a response from you in my inbox, I find myself in shock because I can't believe people like yourself are willing to help strangers like myself. I'm mind-blown. Thanks for your kindness! I'm going to keep fussing around with configurations and hopefully if we ever cross paths on the Internetz again, I'll be much more familiar with Git and Terminal.

^_^

**Comment by lilchen** [comment]
@e2 I just did all of your fixes! IT'S WORKING FOR THE MOST PART. Press/Speaking data is rendering a bit odd, and I did leave out changing 2x to x2 though, I wasn't sure what that revision was meant for.

Regardless, thank you SO MUCH. I'm new to Git and every time I see a response from you in my inbox, I find myself in shock because I can't believe people like yourself are willing to help strangers like me. I'm mind-blown. Thanks for your kindness! I'm going to keep fussing around with configurations and hopefully if we ever cross paths on the Internetz again, I'll be much more familiar with Git and Terminal.

And getting stuck as a designer does stink, it made me feel helpless at first. But reading your responses has taught me a bit about how Git can be used and how debugging works in Terminal!

^_^

**Comment by e2** [comment]
Given you took the time providing the output with debugs (precious!), creating a repo with the problem (precious too!) - helping you has not only been a pleasure, I've learned a lot too.

I'll close this issue once there's at least a good workaround.
