### ISSUE TITLE
Multiple detection of a single deleted file over nfs mount (file >20 mb)

### ISSUE THREAD

**Issue by ryandsouza123** [guard/listen#316]
Hi,
  The listen API when listening to an nfs mount point seems to be detecting a single file multiple number of times when deleted only once. The file sizes are usually > 20 mb ( maybe lesser).
The detections sometimes are outputed infinitely blocking any other modifications or additons within the mounted file system.

The api is called in a ruby script 
OS veriosn of both listening system and mounted file system is SUSE linux.
ruby version :  2.1.6p336
listen gem version : 2.10.0 (polling used)

**Comment by e2** [comment]
Listen has a special environment variable to help debug issues like this: `LISTEN_GEM_DEBUGGING=2`

Some examples of how to use this and interpret the results are here: https://github.com/guard/listen/wiki/Troubleshooting

If you want, you can upload a gist with the output and I'll have a look.

The output may be huge if you have large directories. If so, try copy the files into an empty directory, start listen with `LISTEN_GEM_DEBUGGING=2` to watch *that* directory, immediately delete the file and close listen to avoid too many events.

You can also play around with the parameters (`latency` in this case and `wait_for_delay`) to see if that helps any. A large `latency` will reduce how often the polling happens, while a larger `wait_for_delay` will accumulate more events and remove more duplicates.

**Comment by ryandsouza123** [comment]
Hi,
  I have set the latency to 60 (wait for a minute between polls), but when I use LISTEN_GEM_DEBUGGING=2 , I can see that the monitored directory is polled like it did by default.
which is every second. Is there more required to be specified ?

listener = Listen.to(dir , force_polling: true, only: fil ,latency: 60 , ignore: path) do |modified, added, removed|
  puts "modified absolute path: #{modified}"
  puts "added absolute path: #{added}"
  puts "removed absolute path: #{removed}"
end
listener.start
sleep

dir, path and fil are variables and they seem to be playing their role and working perfectly , but i do not see any delay in polling.
Regards,
Ryan

**Comment by e2** [comment]
Fixed and released (2.10.1). Let me know if you have any other issues. Thanks!
