### ISSUE TITLE
Errors Installing and Running this file (Windows 7)

### ISSUE THREAD

**Issue by cipherrage** [guard/listen#323]
Installing this file via 'gem install...' on windows command line generates the following error:-

Fetching: listen-3.0.0.gem (100%)
Successfully installed listen-3.0.0
1 gem installed
Installing ri documentation for listen-3.0.0...

RDoc::Parser::Ruby failure around line 26 of
lib/listen/logger.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  C:/Ruby193/bin/ruby.exe -c lib/listen/logger.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

        (RDoc::Error) unknown type of %string "i"

ERROR:  While generating documentation for listen-3.0.0
... MESSAGE:   unknown type of %string "i"
... RDOC args: --ri --op C:/Ruby193/lib/ruby/gems/1.9.1/doc/listen-3.0.0/ri lib
--title listen-3.0.0 Documentation --quiet

-------------------------------------------------------------------------------------------------------------------------

When running the "bundle exec guard" command via windows command line the following error is generated:-

C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-3.0.0/lib/listen.rb:2:in `require': C
:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-3.0.0/lib/listen/logger.rb:26: unknown
 type of %string (SyntaxError)
    %i(fatal error warn info debug).each do |meth|
       ^
C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-3.0.0/lib/listen/logger.rb:26: syntax
 error, unexpected $end
    %i(fatal error warn info debug).each do |meth|
       ^
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-3.0.0/lib/listen.rb:2:in
 `<top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/guard-2.12.7/lib/guard.rb:2:in
`require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/guard-2.12.7/lib/guard.rb:2:in
`<top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/guard-2.12.7/bin/_guard-core:3:
in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/guard-2.12.7/bin/_guard-core:3:
in `<main>'

**Comment by e2** [comment]
Ruby 1.9.3 is EOL and no longer maintained. It's best to upgrade to Ruby 2.2.2 (especially for fixes for recent vulnerabilities). For most users, there isn't a big difference between 1.9.3 and 2.0.0, so upgrading shouldn't be any trouble.

**Comment by e2** [comment]
I've updated the README. I was wondering about showing a warning/error, but I'm not sure if that's a good idea. 

Do let me know if you have any other issues, thanks!

**Comment by cipherrage** [comment]
Upgraded to Ruby 2.2.2 and it works perfectly.

Many thanks for your help in this matter.
