### ISSUE TITLE
No Changelog

### ISSUE THREAD

**Issue by bmulholland** [guard/listen#326]
Looking for the Changelog for v3. https://github.com/guard/listen/blob/master/CHANGELOG.md says to check the releases page, but https://github.com/guard/listen/releases only contains release notes for releases < 3.0.0.

**Comment by e2** [comment]
Sorry about that! The draft was supposed to be automatically published, but something went wrong, and I didn't check (like I usually do).

Thanks for letting me know!

**Comment by bmulholland** [comment]
Thanks for the quick fix!
