### ISSUE TITLE
Ignore `node_modules` directory by default 

### ISSUE THREAD

**Issue by e2** [guard/listen#338]
See #337 for details.

**Comment by tubbo** [comment]
Also having an issue related to this that would totally solve my problem:

```
[Thu Jun 02 2016 12:27:01 GMT-0400 (EDT)] WARNING         Directory: /app/ember-client/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources
[Thu Jun 02 2016 12:27:01 GMT-0400 (EDT)] WARNING 
[Thu Jun 02 2016 12:27:01 GMT-0400 (EDT)] WARNING         is already begin watched through: /app/ember-client/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources
[Thu Jun 02 2016 12:27:01 GMT-0400 (EDT)] WARNING 
[Thu Jun 02 2016 12:27:01 GMT-0400 (EDT)] WARNING         MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```

This is currently blocking all development as my Rails server both won't start and prints out an error for every file in node_modules. :(

**Comment by e2** [comment]
I apologize for not adding this in Listen 3.x - Listen 3.x was a major overhaul already, but I could've just browse all the issues and added a rule. Oh, well, I hope I won't forget to make it the default in Listen 4.x..

As a workaround, just ignore it with rules:

https://github.com/guard/listen#ignore--ignore

But ideally you want to only watch directories where you're currently making changes, e.g. selectively watch `app/models`, `app/controllers`, etc.

Overall the flaw is in Node in that it includes modules inside a project. That's as ridiculous as including a '/usr' folder inside every project, with all the development tools and apps possible.

**Comment by ColinDKelley** [comment]
I'm closing this since it is so old. Happy to reopen if there is fresh info.
