### ISSUE TITLE
Do we stilll need the Windows and BSD notes in the README?

### ISSUE THREAD

**Issue by i-give-up** [guard/listen#347]
I'm referring to [this section](https://github.com/guard/listen/blob/master/README.md#on-windows) and the next.

It seems like Thibaud has added the lines in this project's GEMFILE back in September 2013 with commits 95f3a19bbe5cb2bda465f7e98989a0698ffc5708 and e99b7406e94944a6f6bc657ddb8a0535ed0790cc

**Comment by e2** [comment]
Sadly, yes.

First, the project Gemfile in Listen is only for development on the Listen project itself - so it has nothing to do with the Readme.

Second, only OSX (rb-fsevent) and Linux (rb-inotify) optimized adapters are included in Listen's dependencies. So to avoid polling on Windows and BSD, users have to also install the right adapter (wdm or rb-kqueue).

The wdm could be also bundled with Listen, but I'm not sure if it is really a good idea. 

But, thanks for wanting to cut out excess fat from the Readme - I appreciate that very much!
