### ISSUE TITLE
Broken exception handling in darwin adapter

### ISSUE THREAD

**Issue by unjello** [guard/listen#355]
Recent changes cause darwin adapter to crash. `_log_exception` is missing a caller parameter (at least)

**Comment by e2** [comment]
Fixed in: https://github.com/guard/listen/pull/356

Sorry about the issue - I don't have OSX to test. 

There should be 3 parameters (error, lineno, caller).

**Comment by unjello** [comment]
No prob. Thanks for getting back. I guess I just took a look at Base class
```      rescue
        _log_exception 'adapter config failed: %s:%s called from: %s', caller
        raise
      end
```
and since the number of string arguments didn't match I figured the method just only needs caller.

**Comment by e2** [comment]
I'll release soon I hope.
