### ISSUE TITLE
Feature request: on startup, automatically trigger changes since last time Listen was run.

### ISSUE THREAD

**Issue by chrisvel** [guard/listen#366]
I am running listen with ruby and listener (obviously) listens for file changes. Can I somehow trigger the process for already existing items inside the folder ?

```
listener = Listen.to('/Users/user/Downloads') do |modified, added, removed|
  if added
    added.each { |file| FileAction.new(file) unless file.empty? }
  end
end
listener.start 
sleep
```

**Comment by e2** [comment]
I have no idea what you mean by "trigger the process".

I'm guessing that if you add a file, you want to simulate a "modified" event on it.

If so, you probably want to do something like:

```ruby
require 'fileutils'
listener = Listen.to('/Users/user/Downloads') do |modified, added, removed|
    added.each { |file| FileUtils.touch(file) }
end
listener.start 
sleep
```

If you want to simulate a modify event, it's best to actually perform it instead.

**Comment by chrisvel** [comment]
@e2 This must be not a "listen" issue but it's related to. 

The listener service runs and waits for changes (modify, add, remove). Sometimes you might not want to leave it running as a service but instead of this you'd want to run it manually after files have been added to the folder. How could you include those files and process them as "added" ?

**Comment by e2** [comment]
> you'd want to run it manually after files have been added to the folder

I don't understand what you mean by "run it manually after files have been added". 

Explain your use case if you can, because `Listen` has internal filesystem snapshots, so unless you stop `Listen`, it will find added files anyway. This also means: you can't just "simulate" that a file was added.

So explain what you need based on an example.

P.S. `Listen` always passes an array for each argument, so instead of `if added` you probably want `if added.any?` to actually check for added files.

**Comment by e2** [comment]
I think I get it. You probably need a separate script that does the following:

1. Load a list of files to ignore, e.g. `files.txt`. (Empty at first - see next steps).
2. Scan the directory with e.g. `Dir['*.*']`
3. Compare and find which files are added, e.g. `added = Dir['*.*'] - IO.read('files.txt').lines.map(&:chomp)`
4. Run your action on those files, e.g. `added.each { |file| FileUtils.touch(file) }`
5. Add the list of files to ignore next time: `IO.write('files.txt', Dir['*.*'].join("\n"))`

Listen could support this in the near future for you, but right now it doesn't.

I changed the title to keep track of this. It's a very good suggestion for a feature.

**Comment by ColinDKelley** [comment]
Closing this out since it doesn't seem likely that this feature will get built in `listen`.
