### ISSUE TITLE
test broken in ruby 2.3

### ISSUE THREAD

**Issue by thiagovsk** [guard/listen#367]
Hi guys, I was running the tests with ruby 2.3 and I saw this test is broken:

https://travis-ci.org/thiagovsk/listen/jobs/113187615

any suggestion to fix it?

**Comment by thiagovsk** [comment]
i just change 

```
subject { described_class.new('dir1', &block) }
```

to 

```
subject do
  described_class.new('dir1') do |*args|
    myblock.call(*args)
   end
end
```

But I'am not sure if is a good implementation.

**Comment by e2** [comment]
Yes, looks good!

Just create a pull request for it (because of automation/hooks), and I'll gladly merge it.

**Comment by thiagovsk** [comment]
@e2 thanks !

#368
