### ISSUE TITLE
Error installing listen: listen requires ruby version ~> 2.2, version 2.2.3 installed

### ISSUE THREAD

**Issue by Cinderhaze** [guard/listen#382]
On Ubuntu 15.10.

```
usr@ubuntu:~/puppet-vault$ sudo gem install listen -v '3.1.1'
ERROR:  Error installing listen:
        listen requires Ruby version ~> 2.2.
usr@ubuntu:~/puppet-vault$ ruby --version
ruby 2.2.3p173 (2015-08-18) [x86_64-linux-gnu]
usr@ubuntu:~/puppet-vault$ gem --version
2.2.2
```

I'm new to ruby.. Is there any additional logging that is required?

**Comment by e2** [comment]
It's because you're using sudo which uses the system ruby.

Try the following to see the difference:

```
sudo ruby --version
```

I'm guessing that in your situation you don't need the `sudo`.

**Comment by e2** [comment]
Ubuntu ships with an outdated Ruby 2.1. If you really need `sudo` and the system ruby, you can probably just install Ruby 2.2 from a PPA.

**Comment by Cinderhaze** [comment]
```
usr@ubuntu:~/puppet-vault$ sudo ruby --version
[sudo] password for usr:
ruby 2.2.3p173 (2015-08-18) [x86_64-linux-gnu]
```

I was trying to install it with bundler, and bundler wanted me to make sure that it installed correctly.  I had run something as root before and permissions were incorrect on my gem directory, so that's why I was using sudo..

I have my ruby version manually set with /etc/alternates (this is a one-off box that I'm playing around on)

Thanks for your help!

**Comment by e2** [comment]
If you want, the alternative is to install a pre-release version of bundler with `gem install bundler --pre`.

This new version of bundler will automatically use the latest possible version of Listen supporting the Ruby you have.

Have a nice day!

**Comment by Cinderhaze** [comment]
I still see the same behavior with the prerelease version of bundler.  Am I incorrect in my understanding of the ~> 2.2 statement (new to ruby).  I had thought that meant supports ruby 2.2.x.  Does it mean supports ruby up to (but not including) ruby 2.2, aka ruby 2.1.x ?


```
usr@ubuntu:~/puppet-vault$ sudo gem install bundler --pre
Successfully installed bundler-1.12.0
Parsing documentation for bundler-1.12.0
Done installing documentation for bundler after 4 seconds
1 gem installed
usr@ubuntu:~/puppet-vault$ bundle install
Fetching https://github.com/rodjek/rspec-puppet.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies.........
Using rake 11.1.2
Using CFPropertyList 2.2.8
Using addressable 2.4.0
Using json 1.8.3
Using mini_portile2 2.0.0
Using backports 3.6.8
Using require_all 1.3.3
Using stringify-hash 0.0.2
Using excon 0.49.0
Using builder 3.2.2
Using formatador 0.2.5
Using multi_json 1.11.3
Using ipaddress 0.8.3
Using inflecto 0.0.2
Using multipart-post 2.0.0
Using jwt 1.5.4
Using little-plugger 1.1.4
Using memoist 0.14.0
Using os 0.9.6
Using httpclient 2.8.0
Using hurley 0.2
Using mime-types 2.99.1
Using uber 0.0.15
Using retriable 2.1.0
Using thor 0.19.1
Using hocon 0.9.5
Using inifile 2.0.2
Using minitest 5.8.4
Using net-ssh 2.9.4
Using open_uri_redirections 0.2.1
Using trollop 2.1.2
Using rsync 1.0.9
Using unf_ext 0.0.7.2
Using rspec-support 3.1.2
Using diff-lcs 1.2.5
Using net-telnet 0.1.1
Using sfl 2.2
Using coderay 1.1.1
Using ffi 1.9.10
Using facter 2.4.6
Using net-http-persistent 2.9.4
Using net-http-pipeline 1.0.1
Using rb-fsevent 0.9.7
Using lumberjack 1.0.10
Using nenv 0.3.0
Using shellany 0.0.1
Using method_source 0.8.2
Using slop 3.6.0
Using json_pure 1.8.3
Using highline 1.7.8
Using stomp 1.3.5
Using systemu 2.6.5
Using metaclass 0.0.4
Using spdx-licenses 1.1.0
Using netrc 0.11.0
Using puppet-lint 1.1.0
Using websocket 1.2.3
Using vagrant-wrapper 2.0.3
Using bundler 1.12.0
Using puppet-syntax 2.1.0
Using fission 0.5.0
Using launchy 2.4.3
Using jgrep 1.4.0
Using travis-lint 2.0.0
Using nokogiri 1.6.7.2
Using beaker-answers 0.4.2
Using beaker-hiera 0.1.1
Using beaker-pe 0.1.2
Using docker-api 1.28.0
Using fog-core 1.38.0
Using faraday 0.9.2
Using logging 2.1.0
Using representable 2.3.0
Using net-scp 1.2.1
Using unf 0.1.4
Using rspec-core 3.1.7
Using rspec-mocks 3.1.3
Using rspec-expectations 3.1.2
Using ethon 0.9.0
Using rb-inotify 0.9.7
Using notiffany 0.0.8
Using pry 0.10.3
Using hiera 1.3.4
Using mcollective-client 2.8.4
Using mocha 1.1.0
Using metadata-json-lint 0.0.11
Using pusher-client 0.6.2
Using facterdb 0.3.4
Using aws-sdk-v1 1.66.0
Using rbvmomi 1.8.2
Using fog-xml 0.1.2
Using fog-json 1.0.2
Using fog-local 0.3.0
Using fog-vmfusion 0.1.0
Using signet 0.7.2
Using faraday_middleware 0.10.0
Using gh 0.14.0
Using specinfra 2.57.1
Using domain_name 0.5.20160310
Using rspec 3.1.0
Using rspec-its 1.2.0
Using typhoeus 0.8.0
Installing listen 3.1.1

Gem::InstallError: listen requires Ruby version ~> 2.2.
Using puppet 3.8.7
Using aws-sdk 1.66.0
Using fog-atmos 0.1.0
Using fog-ecloud 0.3.0
Using fog-profitbricks 0.0.5
Using fog-terremark 0.1.0
Using fog-voxel 0.1.0
Using fog-aws 0.9.2
Using fog-brightbox 0.10.1
Using fog-dynect 0.0.3
Using fog-google 0.0.9
Using fog-powerdns 0.1.1
Using fog-radosgw 0.0.5
Using fog-riakcs 0.1.0
Using fog-sakuracloud 1.7.5
Using fog-serverlove 0.1.2
Using fog-softlayer 1.1.0
Using fog-storm_on_demand 0.1.1
Using googleauth 0.5.1
Using http-cookie 1.0.2
Using rspec-puppet 2.4.0 from https://github.com/rodjek/rspec-puppet.git (at master@79d5373)
Using serverspec 2.33.0
Using travis 1.8.2
An error occurred while installing listen (3.1.1), and Bundler cannot continue.
Make sure that `gem install listen -v '3.1.1'` succeeds before bundling.
```

**Comment by e2** [comment]
The difference is here:

```
usr@ubuntu:~/puppet-vault$ sudo gem install bundler --pre
```

vs

```
usr@ubuntu:~/puppet-vault$ bundle install
```

In the first case, you're installing bundler into the system gems (as root).

In the second case, you're using the user-installed bundler (so it's the old version).


You'll see the difference in:

`sudo bundler --version`

vs

`bundler --version`

If you're having permission issues, it's best to solve those first.

If you want to know the differences between root and user gem locations, use the `gem env` command:

`sudo gem env`

vs

`gem env`

Again, you probably want to fix those permissions. Otherwise, you're just using 2 different Ruby setups here (with and without sudo). I'd avoid sudo unless whatever you're using absolutely needs it (I doubt it).

You'll notice in the output of `gem env` that you should have some of the gem directories in a user-writable location. These will override earlier gem locations.

You can check where a gem is installed with e.g.

`sudo gem contents bundler`

vs 

`gem contents bundler`

Hope that helps.

**Comment by Cinderhaze** [comment]
Thanks for the great feedback!  The bundler version isn't the problem..

```
usr@ubuntu:~$ sudo bundler --version
Bundler version 1.12.0
usr@ubuntu:~$ bundler --version
Bundler version 1.12.0

```

Right now I've switched to trying to use rbenv to build/install ruby to make sure it isn't a problem with the ubuntu packaged version.  I'll let you know if that solves my problem or not.

Thanks for your great contributions to the community, and for helping me out with my questions/problems!

**Comment by e2** [comment]
Just as information: Ruby 2.2.4 fixes a serious security vulnerability, while 2.2.5 fixes further bugs.

The best place to find out which version of Ruby to install is: ruby-lang.org

https://www.ruby-lang.org/en/news/2016/04/26/ruby-2-2-5-released

I package managers aren't keeping up, it's best to notify them. (Though they usually track such announcements).

Tools like rbenv and RVM help because they let you install any version quite conveniently.

**Comment by Cinderhaze** [comment]
I was able to duplicate my issue with Docker..

https://gist.github.com/Cinderhaze/6d0a9d2cbd3804218d5e25e4c08e4e48

**Comment by e2** [comment]
@Cinderhaze - thanks!

Even Bundler 1.12 doesn't seem to resolve dependencies of dependencies which rely on a newer Ruby.

I've just released Listen 3.1.3. It has a few fixes for JRuby, which is 2.2.3. This also means that Listen will now install on Ruby 2.2.3, but you should instead get a vulnerability warning.

I ran `bundle update` on your docker image and it installs correctly now.

Let me know if you have any other issues.

P.S. I strongly suggest you upgrade to at least Ruby 2.2.4 or 2.2.5.

**Comment by e2** [comment]
You might want to use this PPA: `sudo apt-add-repository ppa:brightbox/ruby-ng` and `sudo apt-get install ruby2.2` (which currently will give you 2.2.4).

**Comment by neurogenesis** [comment]
Anyone coming from the Chef / Test Kitchen side might have problems. Chef-DK uses older versions of Ruby (2.1.8 i think for the current release of Chef Developer Kit).

**Comment by e2** [comment]
@neurogenesis - RubyDep allows Ruby 2.0.0 for now, see: https://rubygems.org/gems/ruby_dep and https://github.com/e2/ruby_dep/pull/9

**Comment by kamrankausar** [comment]
I am using 
Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.16.1.el7.x86_64
      Architecture: x86-64

ERROR:  Error installing java:
	java requires Ruby version >= 2.1.0.
As root 
# ruby --version
O/P- ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
Can any one help to solve this
