### ISSUE TITLE
Cannot install on JRuby due to dependency on Ruby 2.2.4

### ISSUE THREAD

**Issue by e2** [guard/listen#386]
### Problem

There's no JRuby available version compatible with Ruby >= 2.2.4, so Listen doesn't install.

(Ruby 2.2.3 has a security vulnerability that doesn't affect JRuby and `ruby_dep` doesn't take JRuby into account yet).

### Workaround

Install jruby-head (e.g. using RVM: `rvm install jruby-head`).

**Comment by e2** [comment]
Ideally, `Bundler` would install the latest supported Listen for your version automatically (probably needs a bug report), but this doesn't happen because of dependencies. (Bundler probably just isn't smart enough yet).

Otherwise, I'm not sure how to set `required_ruby_version` so that it's `>= 2.2.4` on MRI and `>= 2.2.3` on JRuby. The best solution would probably be to support Ruby 2.2.3 by `ruby_dep` gem. See: https://github.com/e2/ruby_dep/issues/4

**Comment by e2** [comment]
Fixed in https://github.com/e2/ruby_dep/pull/6

**Comment by perlun** [comment]
See also #389.

**Comment by e2** [comment]
In case anyone else stumbles upon this, I've started a wiki page for this here: https://github.com/guard/listen/wiki/Support-for-older-versions-of-Ruby
