### ISSUE TITLE
Fallback to polling on macOS 10.11.5

### ISSUE THREAD

**Issue by danez** [guard/listen#404]
I try running rsync-auto of vagrant which uses this gem version 3.0.8.

When i start it it reports:

```
I, [2016-06-21T16:47:28.867191 #71911]  INFO -- : Listen loglevel set to: 0
I, [2016-06-21T16:47:28.867278 #71911]  INFO -- : Listen version: 3.0.8
D, [2016-06-21T16:47:33.058924 #71911] DEBUG -- : Adapter: considering polling ...
D, [2016-06-21T16:47:33.059011 #71911] DEBUG -- : Adapter: considering optimized backend...
rb-fsevent > 0.9.4 no longer supports OS X 10.6 through 10.8.

Please add the following to your Gemfile to avoid polling for changes:
  require 'rbconfig'
  if RbConfig::CONFIG['target_os'] =~ /darwin(1[0-3])/i
    gem 'rb-fsevent', '<= 0.9.4'
  end
D, [2016-06-21T16:47:33.065075 #71911] DEBUG -- : Adapter: falling back to polling...
```

uname -a

```
Darwin MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

I expect fsevents to work on the latest macOS version.

**Comment by danez** [comment]
When I try this in the ruby prompt it works. This is basically the same as the listener is doing to check the os version.

```
darwin_version = RbConfig::CONFIG['target_os'][/darwin(?<major_version>1\d+)/i, :major_version] or Kernel.warn "die"
Kernel.warn "correct" if darwin_version.to_i >= 13
```

I'm also not a ruby dev so don't know how to debug this further.

**Comment by danez** [comment]
Seems this is still valid. Now with vagrant 1.8.5 which uses the listen gem 3.1.5 it is still reporting macOS 10.11 as an older version.

**Comment by danez** [comment]
Maybe using using uname like ohai does: https://github.com/chef/ohai/blob/master/lib/ohai/plugins/kernel.rb

Or use ohai itself.

**Comment by e2** [comment]
I don't have OSX to test. I exclusively use Linux.

@vaz - could you take a look here?

**Comment by e2** [comment]
What is the output of `uname -v` or `uname -s` or `uname -r` ?

**Comment by e2** [comment]
What does `RbConfig::CONFIG["host_os"]` say?

**Comment by danez** [comment]
I'm using macOS 10.11.6

`uname -v:` `Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64`
`uname -s:` `Darwin`
`uname -r:` `15.6.0`

`RbConfig::CONFIG["target_os"]:` `darwin12.0`
`RbConfig::CONFIG["host_os"]:` `darwin12.6.0`

**Comment by e2** [comment]
Can you try:

```ruby
gem 'listen', '3.0.6'
```

and see if events work properly?

**Comment by danez** [comment]
No sorry, I don't know how to replace a gem. I tried cloning the gem in the gems directory, but then  ruby can't find the gem.

**Comment by e2** [comment]
Sorry, I keep forgetting you're using Vagrant.

**Try the following first:**

Locate the source files within Vagrant and change the line in the file here:

https://github.com/guard/listen/blob/master/lib/listen/adapter/darwin.rb#L26

and make it `return true`.

Then, check if it responds to changes.

I simply don't know if rb-fsevent works properly on your OSX version.

You can try this outside listen by running the following example in Ruby:

https://github.com/thibaudgg/rb-fsevent#singular-path

**Comment by danez** [comment]
Ok I did that, the message went away, but it seems it is not using inotify as ruby uses 100% cpu and changes take forever to be detected. :(

**Comment by danez** [comment]
Although when i install rb-notify by myself and do the example you linked it seems to work just fine. (This is using the native ruby version though)
```
❯ irb
irb(main):001:0> require 'rb-fsevent'
=> true
irb(main):002:0> 
irb(main):003:0* fsevent = FSEvent.new
=> #<FSEvent:0x007f9a458f7af0>
irb(main):004:0> fsevent.watch Dir.pwd do |directories|
irb(main):005:1*   puts "Detected change inside: #{directories.inspect}"
irb(main):006:1> end
=> []
irb(main):007:0> fsevent.run
Detected change inside: ["/community/"]
Detected change inside: ["/community/.git/"]
Detected change inside: ["/community/.idea/"]
Detected change inside: ["/community/.idea/"]
Detected change inside: ["/community/.git/"]
Detected change inside: ["/community/.git/"]
Detected change inside: ["/community/", "/community/.idea/"]
Detected change inside: ["/community/.git/"]
Detected change inside: ["/community/.idea/"]
```

**Comment by e2** [comment]
> Ok I did that, the message went away, but it seems it is not using inotify as ruby uses 100% cpu and changes take forever to be detected. :(

That shouldn't happen. If you disabled the check and the fsevent thing works, then it should work anyway.

The newest version of Vagrant should be using Listen 3.1.5. I don't know how you installed Vagrant, but maybe `gem update listen` should give you Listen 3.1.5.

**Comment by benprew** [comment]
I'm having this issue too, running vagrant 1.8.5 with listen 3.1.5.

But it looks like the embedded vagrant uses rb-fsevent-0.9.7:

```./embedded/gems/cache/rb-fsevent-0.9.7.gem```

I was looking at the gemspec for listen, shouldn't it be specifying the version based on the OS version?  Like a platform-specific dependency?  

https://en.wikibooks.org/wiki/Ruby_Programming/RubyGems#How_to_install_different_versions_of_gems_depending_on_which_version_of_ruby_the_installee_is_using

@e2, I'd be happy to dig into this a little if you think that sounds like the right direction.


For reference, here's the error:


```rb-fsevent > 0.9.4 no longer supports OS X 10.6 through 10.8.

Please add the following to your Gemfile to avoid polling for changes:
  require 'rbconfig'
  if RbConfig::CONFIG['target_os'] =~ /darwin(1[0-3])/i
    gem 'rb-fsevent', '<= 0.9.4'
  end
[Listen warning]:
  Listen will be polling for changes.Learn more at https://github.com/guard/listen#listen-adapters.
rb-fsevent > 0.9.4 no longer supports OS X 10.6 through 10.8.

Please add the following to your Gemfile to avoid polling for changes:
  require 'rbconfig'
  if RbConfig::CONFIG['target_os'] =~ /darwin(1[0-3])/i
    gem 'rb-fsevent', '<= 0.9.4'
  end```

**Comment by benprew** [comment]
Hmm.. I think it has something to do with the embedded version of ruby that Vagrant ships with.  Here's my system ruby:

```
benprew@faywray ~> which ruby
/usr/local/bin/ruby
benprew@faywray ~> which irb
/usr/local/bin/irb
benprew@faywray ~> irb
irb(main):001:0>
benprew@faywray ~> ruby -v
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-darwin15.0]
benprew@faywray ~> irb
irb(main):001:0> puts RbConfig::CONFIG['target_os']
darwin15.0
```

But the vagrant ruby:

```
===========>target_os: darwin12.0
```

**Comment by danez** [comment]
> Locate the source files within Vagrant and change the line in the file here:
> https://github.com/guard/listen/blob/master/lib/listen/adapter/darwin.rb#L26
> and make it return true.
> Then, check if it responds to changes.
> I simply don't know if rb-fsevent works properly on your OSX version.

I again tried this and it seems that rb-fsevent works fine now, picking up changes immediately and no cpu usage. Not sure what happened the first time. (Maybe I had some other changes in the code).

@e2 Can you think about any possible solution?

**Comment by e2** [comment]
I don't have/own/use OSX to reproduce the problem, etc.

There used to be issues with certain file names in OSX (upper/lower
case). There might be some debugging options available for rb-fsevent.

Overall, you can always check if bare-bones rb-fsevent works first
(copy the example from the rb-fsevent README).

Listen did have issues when watching multiple directories once (and
that was Listen's fault - my fault).

Other than that, I'm unaware of stuff on OSX (I use Linux
exclusively).

Listen also has a debugging mode - but if Listen isn't getting any
events, then it can't do anything.

However, if there's any way I can detect (at least) such rb-fsevent
issues, I'd be glad to add code in Listen to help people avoid
frustrations.
