### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by JIucToyxuu** [guard/listen#406]
Hello! I see 'ERROR -- : exception while processing events: wrong number of arguments (0 for 1)' error when launch rspec tests.
I think source of this issue - [ https://github.com/guard/listen/blob/master/lib/listen/event/loop.rb#L96];

**Comment by e2** [comment]
Yes, I think it should be `_sleep` not `sleep`.

**Comment by e2** [comment]
What gems are you using? Do you have any that could be defining `sleep`? Do you have a way of reproducing the problem?

**Comment by ColinDKelley** [comment]
I believe this has been fixed for a while.
