### ISSUE TITLE
 Issues with Ruby version >=2.2.3, <2.2.5 for listen v3.1.5

### ISSUE THREAD

**Issue by paulgoetze** [guard/listen#414]
The latest [ruby_dep](https://rubygems.org/gems/ruby_dep/versions/1.4.0) release (v1.4.0) requires Ruby version >=2.2.5. Version [3.1.5](https://rubygems.org/gems/listen/versions/3.1.5) of listen depends on ruby_dep ~> 1.2 which can also be resolved to ruby_dep v1.4.

This leads to issues when resolving the dependencies for listen when using Ruby version >=2.2.3 and <2.2.5.

```
Resolving dependencies...
ruby_dep-1.4.0 requires ruby version >= 2.2.5, which is incompatible with the
current version, ruby 2.2.3p173
```

Should listen require min Ruby version >= 2.2.5 as well or just depend on ruby_dep ~> 1.4?

**Comment by e2** [comment]
Thanks for letting me know.

Yes, if you don't care about Ruby < 2.2.5, you can just lock ruby_dep to '~> 1.4'.

Using SemVer here to solve this is the right thing to do.

I'll likely have updates for ruby_dep and listen soon though.

It's a tricky situation. Overall, people should be using either: `listen 3.1` + `ruby_dep 1.4` or `listen 3.0` + `ruby_dep 1.3`.

I'll have to update the README for Listen to mention this.

**Comment by ColinDKelley** [comment]
Ok to close this issue?
