### ISSUE TITLE
outdated information

### ISSUE THREAD

**Issue by ashmaroli** [guard/listen#422]
Found this [outdated info](https://github.com/jekyll/jekyll/blob/master/docs/_docs/troubleshooting.md#liquid) hidden in our documentation (`Liquid 2.0 is not latest version` but rest of the section is still valid.)

Would make a fine specimen for first-time-contributors. (?)

/cc @quiltbag, @DirtyF

**Comment by quiltbag** [comment]
noted! but why is this in the `guard/listen` repo?

**Comment by ashmaroli** [comment]
Oh my..!! What a mega-blunder..!! :man_facepalming:
