### ISSUE TITLE
No such file or directory @ realpath_rec - /var/www + listen gem

### ISSUE THREAD

**Issue by sampath419** [guard/listen#425]
Modification of symlink is not working in rails listen gem while deploying application using capistrano deployment, every time we generating new files in release directory symlink is pointing to current folder but listen is looking for older directory.
very first time creating symlink working fine but second time modification of symlink listen shows error as 

In browser while hitting the server we are getting errir as 
"Errno::ENOENT No such file or directory @ realpath_rec - /var/www/releases/20170306..."

listen (3.0.8) lib/listen/adapter/config.rb:17:in `realpath'
listen (3.0.8) lib/listen/adapter/config.rb:17:in `realpath'
listen (3.0.8) lib/listen/adapter/config.rb:17:in `block in initialize'
listen (3.0.8) lib/listen/adapter/config.rb:16:in `map'
listen (3.0.8) lib/listen/adapter/config.rb:16:in `initialize'

Note: cap deploy command for symlink -
 execute "cd /var/www/retailrecycle && ln -s ./releases/#{File.basename release_path} current"

Thanks for help

**Comment by CodingAnarchy** [comment]
I have the same issue, which is causing some users to run into that error in my staging environment.  It's happening somewhat sporadically though.

**Comment by ColinDKelley** [comment]
I'm hoping that other recent bug fixes have addressed this issue, so I'm going to close it.
