### ISSUE TITLE
Not tracking directory renaming or removal

### ISSUE THREAD

**Issue by thorsteneckel** [guard/listen#426]
Hi there,

as stated [here](https://github.com/guard/guard/issues/866) I have some issues with the tracking of renaming and removing folders:

When removing or renaming a folder `listen` doesn't trigger any addition, modification or removal methods.

Folder structure is:
```
folder0
  folder1
    folder2
      file.rb
```

Now if I rename or delete `folder1` I see (via debug mode) `listen` to trigger an event for the `folder0` directory but no method call is triggered. Seems that `listen` isn't noticing that the folder was removed. Funny thing is when renaming the folder it triggers the add call for the "new" `file.rb`. 

After some debugging and playing around I managed to get it working for my case:

```diff
--- a/lib/listen/record.rb
+++ b/lib/listen/record.rb
@@ -45,8 +45,7 @@ module Listen
         if [nil, '', '.'].include? rel_path.to_s
           tree
         else
-          tree[rel_path.to_s] ||= _auto_hash
-          tree[rel_path.to_s]
+          _sub_dir_entries(rel_path)
         end

       result = {}
@@ -114,5 +113,20 @@ module Listen
     rescue SystemCallError
       _fast_unset_path(entry.relative, entry.name)
     end
+
+    def _sub_dir_entries(rel_path)
+      result = {}
+      tree.each do |path, meta|
+        next if !path.start_with?(rel_path)
+
+        if path == rel_path
+          result.merge!(meta)
+        else
+          sub_path = path.sub(%r{\A#{rel_path}/?}, '')
+          result[sub_path] = meta
+        end
+      end
+      result
+    end
   end
 end
```

With this change all entries get checked recursively.

Some feedback would be nice.

PS: I could provide a Guard file for testing purposes.

**Comment by Neosublimation** [comment]
I can confirm this bug. On Windows 7 at least. Using WDM.

In my test case I removed a folder with two files in it and instead of triggering the folder removal event it repeated an older remove event on a file that didn't exist anymore at all.

Didn't test the proposed fix, but I hope you will test and integrate it, soon.

**Comment by JerryGreen** [comment]
Huh, I'm not the only one! Let me describe how I'm experiencing this...

I'm listening my `~/Downloads` folder. And I have this structure inside it:
```
test1/
test1/file.svg
test1/test2/
test1/test2/file.svg
test1/test2/test3/
test1/test2/test3/file.svg
test1/test2/test3/test4/
test1/test2/test3/test4/file.svg
```
When I remove these files (in any folder) - it's all ok. It's working well.
When I remove folders `test1` or `test2` - it's all ok too. Callbacks fired correctly.
But when I remove folders `test3` or `test4` - it's all silent. No callbacks fired.

I'm using:
```
listen 3.0.8
macos 10.12.6
```

Looks like this issue may be related to this problem:
https://github.com/guard/listen/issues/424

**Comment by parruda** [comment]
I just ran into this problem trying to use listen to monitor a tree.
I get no event when directories are removed.
I used the same tree as @JerryGreen above:
```
test1/
test1/file.svg
test1/test2/
test1/test2/file.svg
test1/test2/test3/
test1/test2/test3/file.svg
test1/test2/test3/test4/
test1/test2/test3/test4/file.svg
```
I am on OSX Mojave.

**Comment by parruda** [comment]
I just want to say I applied the patch posted by @thorsteneckel and it works.

**Comment by JerryGreen** [comment]
@parruda posted where? What patch?

**Comment by thorsteneckel** [comment]
@parruda - first comment. Here again generated freshly via `git diff`:

```diff
diff --git a/lib/listen/record.rb b/lib/listen/record.rb
index ad374ce..8add4d4 100644
--- a/lib/listen/record.rb
+++ b/lib/listen/record.rb
@@ -45,8 +45,7 @@ module Listen
         if [nil, '', '.'].include? rel_path.to_s
           tree
         else
-          tree[rel_path.to_s] ||= _auto_hash
-          tree[rel_path.to_s]
+          _sub_dir_entries(rel_path)
         end
 
       result = {}
@@ -114,5 +113,20 @@ module Listen
     rescue SystemCallError
       _fast_unset_path(entry.relative, entry.name)
     end
+
+    def _sub_dir_entries(rel_path)
+      result = {}
+      tree.each do |path, meta|
+        next if !path.start_with?(rel_path)
+
+        if path == rel_path
+          result.merge!(meta)
+        else
+          sub_path = path.sub(%r{\A#{rel_path}/?}, '')
+          result[sub_path] = meta
+        end
+      end
+      result
+    end
   end
 end
```

This fix works for me pretty well. I'll go and create a merge request from it 👍

**Comment by ColinDKelley** [comment]
It looks like @thorsteneckel 's patch above was [applied some time ago](https://github.com/guard/listen/blob/48c88715646c3d1b9933c9e7c8110a9e33ff1900/lib/listen/record.rb#L46-L72), so I'm going to close out this issue.
