### ISSUE TITLE
Can't restart listener after it has been stopped

### ISSUE THREAD

**Issue by rlue** [guard/listen#429]
This problem arose and was fixed in issue #185, though it seems that the design of the library has changed a lot since then.

```
>> listener = Listen.to('/Users/rlue/Desktop') { puts 'something happened!' }
>> listener.start
>> listener.processing?     # => true
>> listener.stop
>> listener.start
>> listener.processing?     # => false
```

FWIW, I'm on Mac OS 10.11 El Capitan / Ruby 2.4.0p0.

**Comment by rlue** [comment]
So I've taken a closer look, and while I still don't understand all the different moving parts of this library, I think I'm closer to seeing what's going on here.

### Problem 1: `Listener#start` does nothing in `:stopped` state

This is the `#start` method of the `Listen::Listener` class:

```ruby
def start
  transition :backend_started if state == :initializing
  transition :frontend_ready if state == :backend_started
  transition :processing_events if state == :frontend_ready
  transition :processing_events if state == :paused
end
```

To my understanding, this method initiates a (chain of) state transitions, each of which comes with its own setup behavior. However, no line exists for the condition `state == :stopped`.

This problem can be solved by adding the following line to the top of the method:

```ruby
transition :backend_started if state == :stopped
```

### Problem 2: Filesystem changes continue to be collected in the `:stopped` state

With the fix above, Listener instances can be stopped and started normally, but filesystem changes continue to be collected while the listener is stopped. In effect, stopping and restarting the listener is no different from pausing and unpausing it –  when the listener is restarted, the listener callback will be executed immediately.

Under the hood, stopping the listener is supposed to initiate two actions: `backend.stop` and `processor.teardown`. The `backend` object delegates the `#stop` method to the adapter class, which contains the following definition for the method:

```ruby
def stop
  _stop
end

private

def _stop
end
```

Not quite sure what's supposed to go in there, though.

**Comment by ColinDKelley** [comment]
I believe this is fixed in the state machine simplification/redesign of v3.3.0. If a problem comes up in that version or later, please open a new issue.
