### ISSUE TITLE
wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by wbotelhos** [guard/listen#431]
Stack:

`rails 5.1.2`
`ruby 2.4.1`
`guard 2.14.1`

Error:

```
E, [2017-06-28T22:18:52.571551 #4575] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:41:in `block (2 levels) in configure'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/rb-fsevent-0.10.0/lib/rb-fsevent/fsevent.rb:75:in `run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:71:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:70:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'

E, [2017-06-28T22:18:52.572793 #4575] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/base.rb:41:in `block (2 levels) in configure'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/rb-fsevent-0.10.0/lib/rb-fsevent/fsevent.rb:75:in `run'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:71:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:81:in `block (2 levels) in _run_workers_in_background'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:70:in `_run_worker'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:81:in `block (2 levels) in _run_workers_in_background'
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

**Comment by jacob-hedengren** [comment]
Today suddenly I get the same error!

**Comment by moioo** [comment]
Me too!
Rails 5.1.2 ruby 2.4.0

**Comment by tpbowden** [comment]
Also getting this error, ruby 2.4.1 rails 5.1.2

**Comment by moioo** [comment]
Me too, ruby 2.4.1 rails 5.1.2

**Comment by tpbowden** [comment]
This is an issue with the rb-fsevent gem. A temporary workaround is to add `  gem "rb-fsevent", "0.9.8"` to your gemfile.

**Comment by StanBright** [comment]
Away from guard, I faced another issue (by using rb-fsevent >= 0.10) - classes weren't reloaded in development mode. I.e. I had to restart the whole server for a change to be present.

**Comment by crawfoal** [comment]
@tpbowden, @StanBright  I don't see an issue open in the rb-fsevent project... should one be opened there? I don't know enough about the issue to open it.

**Comment by tpbowden** [comment]
I don't know if it's an issue or just a breaking change in their API - they are still < 1.0 and incremented by a minor version so I guess this would be acceptable on their part.

**Comment by 9mm** [comment]
36 seconds ago eh im late to the party

**Comment by thibaudgg** [comment]
Could you please give a try to the rb-fsevent 0.10.2 release, this issue has been addressed. More info on https://github.com/thibaudgg/rb-fsevent/issues/76.

**Comment by zx1986** [comment]
@thibaudgg rb-fsevent 0.10.2 works fine with me, thank you!

`bundle update rb-fsevent`

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
guard (2.14.1)
rails (4.2.3)

**Comment by marcusbey** [comment]
I tried the rb-fservent 0.10.2 which didn't work. I had to change it to  **gem "rb-fsevent", "0.9.8"** and now my livereload works perfectly fine.

**Comment by ttilley** [comment]
@tpbowden - the API change inspired the minor version bump but I thought it was safer than it actually was due to proc blocks ignoring extra parameters. lambdas and methods converted to blocks are not so forgiving about arity differences. The callback's arity is now checked before passing in either just path data, or paths with extended metadata. 

In short, I goofed... but got a fix out as quickly as possible.

**Comment by tpbowden** [comment]
@ttilley I think the issue was more down to listen having its dependencies only constrained on minor versions - something which is now required in Rails by default should probably not be blindly brining in updates from other gems.

**Comment by wbotelhos** [comment]
`rb-fsevent 0.10.2` works.
Thank you! (:

**Comment by rickychilcott** [comment]
Working for me too. Thank you!

**Comment by kumarn33** [comment]
rb-fsevent 0.10.2 works. Thank you! (:

**Comment by ttilley** [comment]
closing this issue on listen. if any of you experience further issues with rb-fsevent, please open them on my tracker for rb-fsevent. I apologise for any inconvenience the earlier 0.10 releases have caused.
