### ISSUE TITLE
I cannot watch Sass  on cloud9 even thought i have  the gems installed  

### ISSUE THREAD

**Issue by CarlasHub** [guard/listen#445]
i 've been running in this problem and i ran all the commands suggested and i got the same error continually. Any idea what is the problem here and how can i fix this? 

![sassproblem](https://user-images.githubusercontent.com/34892979/39663024-4457c45c-5063-11e8-93a5-504dc80ab6e3.png)

**Comment by CarlasHub** [comment]
```
^Ccarlagoncalves:~/workspace (master) $ gem pristine gem-wrappers --version 1.2.7
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored gem-wrappers-1.2.7
carlagoncalves:~/workspace (master) $ gem regenerate_binstubs
try also: gem pristine --binstubs
bundler 1.16.1
executable-hooks 1.3.2
listen 3.1.5
rake 12.0.0
rdoc 5.0.0
rubygems-update 2.7.6
carlagoncalves:~/workspace (master) $ sass --watch styles.sass:styles.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
[Listen warning]:
  Listen will be polling for changes. Learn more at https://github.com/guard/listen#polling-fallback.
```

**Comment by junaruga** [comment]
@CarlasHub which version of sass, are you using?

https://rubygems.org/gems/sass/versions/3.5.0
`sass` started to use `sass-listen` instead of `listen` from sass-3.5.0.
`sass-listen` is a fork for sass v3.0 branch.

**Comment by ColinDKelley** [comment]
As mentioned above, this appears to be an issue with https://github.com/sass/listen, not https://github.com/guard/listen. `sass-listen` is now end-of-life.
