### ISSUE TITLE
Please add some protection to the wiki pages

### ISSUE THREAD

**Issue by donnykurnia** [guard/listen#448]
I encounter warning on my computer and it has a link to https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

When I visit the page, the content has been replaced by someone else. I have managed to revert the page content into the last revision.

This wiki page is important and should be protected from further vandal or unauthorized edit by non-contributor.

**Comment by rymai** [comment]
@donnykurnia Done, thanks!

<img width="731" alt="screen shot 2018-06-05 at 15 39 00" src="https://user-images.githubusercontent.com/1168/40979627-992de66a-68d6-11e8-8671-b6a263c79e52.png">
