### ISSUE TITLE
Listen's use of Digest::MD5 breaks support on FIPS enabled machines

### ISSUE THREAD

**Issue by ruckc** [guard/listen#452]
Please review usage of Digest::MD5 and migrate to a different hash algorithm that is not disabled in when FIPS is enabled.

```
$ rails server
=> Booting Puma
=> Rails 5.2.1 application starting in development
=> Run `rails server -h` for more startup options
md5_dgst.c(78): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
Aborted
```

**Comment by ioquatix** [comment]
What is the best solution to this problem?

**Comment by ruckc** [comment]
Replacing Digest::MD5 with a modern hashing algorithm such as Digest::SHA2 is the easy answer.  Long term though, its ideal to support configurable algorithms for future proofing.

**Comment by souravb65** [comment]
Is there a plan in the near future to use Digest::SHA2 and make it FIPS enabled?

**Comment by ioquatix** [comment]
Sure, do you have time to submit a PR?

**Comment by souravb65** [comment]
Sure. I can give it a try. Looks like I don't have permission to create my feature branch. Can you please grant me permission?

**Comment by ioquatix** [comment]
Please create a fork and submit a PR. If you need more help, please let me know.

**Comment by ColinDKelley** [comment]
@souravb65 Here's a branch: https://github.com/guard/listen/pull/541 Tests are green!

**Comment by ColinDKelley** [comment]
Considering this fixed.

**Comment by souravb65** [comment]
Awesome @ColinDKelley making these changes. I did the changes but due to my machine issue was not able to test to push those.

**Comment by ColinDKelley** [comment]
No problem, @souravb65. Thanks for the nudge to get this fixed and closed.

**Comment by ioquatix** [comment]
@ColinDKelley Thanks for your effort maintaining this gem.
