### ISSUE TITLE
Not working in GrapeAPI

### ISSUE THREAD

**Issue by masong2012** [guard/listen#468]
listener = Listen.to(File.expand_path('../app/apis', __dir__), only: /\.rb$/) do |modified, added, removed|
      modified.each do |path|
           puts path
           load path
      end
end

listener.start

change some files in app/apis dir, it puts the change file path, but the grape return the old code.
how can i make it work with grape??

**Comment by ColinDKelley** [comment]
It's been a couple years with no discussion here, so I'm going to close this issue.
