### ISSUE TITLE
Ruby 3 support

### ISSUE THREAD

**Issue by yahonda** [guard/listen#489]
https://github.com/ruby/ruby/commit/21c62fb670b1646c5051a46d29081523cd782f11 bumps Ruby master branch version to 3.0.0. I've found listen gem is not allowed to install on Ruby 3.0.0dev environment.

* Steps to reproduce 

```
$ ruby -v
ruby 3.0.0dev (2020-08-31T08:18:14Z master 3e1aea4613) [x86_64-linux]
$ gem -v
3.2.0.rc.1

$ gem install listen
Fetching listen-3.2.1.gem
ERROR:  Error installing listen:
	The last version of listen (>= 0) to support your Ruby & RubyGems was 3.0.8. Try installing it with `gem install listen -v 3.0.8`
	listen requires Ruby version ~> 2.2, >= 2.2.7. The current ruby version is 3.0.0.dev.
```

* required_ruby_version does not allow Ruby 3
https://github.com/guard/listen/blob/debf5cbec3fbba7c0ea9f05f9868af2412b4a828/listen.gemspec#L25

**Comment by deepj** [comment]
@ioquatix Hello, is it possible to release a new minor version of `listen` only with this change? Right now this gem blocks testing any Rails application with` Ruby 3.0.0-preview1`

**Comment by ioquatix** [comment]
Sure

**Comment by mrlevitas** [comment]
Looking forward for this fix to be released.

**Comment by marcandre** [comment]
> Looking forward for this fix to be released.

Me too...
