### ISSUE TITLE
DSPACE MIRAGE2 [WARNING] ERROR:  Error installing C:\Users\...\.m2\repository\rubygem s\rb-inotify\0.10.1\rb-inotify-0.10.1.gem:

### ISSUE THREAD

**Issue by arrepol1976** [guard/listen#499]
Hi:
In DSpace 5.7 version, when compiling the Mirage 2 theme I get the following error, the log is:

i use these commands:
mvn package -Dmirage2.on=true
mvn -U clean package -Dmirage2.on=true 
mvn package -Dmirage2.on=true -Dmirage2.deps.included=false

\npm
     [echo] GEM_PATH=C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems
     [echo] GEM_HOME=C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems
     [echo] mirage2.deps.included=true
     [echo] grunt.color.scheme=classic_mirage_color_scheme
     [echo] grunt.environment=prod
     [echo] source=C:\dspace-5.7-src-release\dspace\modules\xmlui-mirage2/src/ma
in/webapp/themes/
[INFO] Executed tasks
[INFO]
[INFO] --- gem-maven-plugin:1.0.6:initialize (default) @ xmlui-mirage2 ---
[INFO] Successfully installed sass-3.3.14
[INFO]     Compass is charityware. If you love it, please donate on our behalf a
t http://umdf.org/compass Thanks!
[INFO] Successfully installed compass-1.0.1
[INFO] Successfully installed compass-core-1.0.3
[INFO] Successfully installed multi_json-1.15.0
[INFO] Successfully installed compass-import-once-1.0.5
[INFO] Successfully installed chunky_png-1.3.12
[INFO] Successfully installed rb-fsevent-0.10.4
[WARNING] ERROR:  Error installing C:\Users\Administrador\.m2\repository\rubygem
s\rb-inotify\0.10.1\rb-inotify-0.10.1.gem:
[WARNING]       rb-inotify requires Ruby version >= 2.2.
[WARNING] ERROR:  Error installing C:\Users\Administrador\.m2\repository\rubygem
s\ffi\1.13.1\ffi-1.13.1.gem:
[INFO] 7 gems installed
[WARNING]       ffi requires Ruby version >= 2.3.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DSpace Addon Modules ............................... SUCCESS [  1.320 s]
[INFO] DSpace Kernel :: Additions and Local Customizations  SUCCESS [  6.549 s]
[INFO] DSpace XML-UI Mirage2 Theme :: Local Customisations  FAILURE [ 42.170 s]
[INFO] DSpace XML-UI (Manakin) :: Local Customizations .... SKIPPED
[INFO] DSpace JSP-UI :: Local Customizations .............. SKIPPED
[INFO] DSpace RDF :: Local Customizations ................. SKIPPED
[INFO] DSpace REST :: Local Customizations ................ SKIPPED
[INFO] DSpace SWORD :: Local Customizations ............... SKIPPED
[INFO] DSpace SWORD v2 :: Local Customizations ............ SKIPPED
[INFO] DSpace SOLR :: Local Customizations ................ SKIPPED
[INFO] DSpace OAI-PMH :: Local Customizations ............. SKIPPED
[INFO] DSpace Assembly and Configuration .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by ColinDKelley** [comment]
The 3 errors that seem to be listed here are:
```
[WARNING] ERROR: Error installing C:\Users\Administrador.m2\repository\rubygem
s\rb-inotify\0.10.1\rb-inotify-0.10.1.gem:
[WARNING] ERROR: Error installing C:\Users\Administrador.m2\repository\rubygem
s\ffi\1.13.1\ffi-1.13.1.gem:
```
and
```
[INFO] DSpace XML-UI Mirage2 Theme :: Local Customisations FAILURE [ 42.170 s]
```
There's not enough detail to debug any of those. Perhaps there is a log file that has the details?

And in any case, they don't appear to be failures of `listen`, so I'm going to close this issue.
