### ISSUE TITLE
Failing bundle install on ruby3.0.0.p0

### ISSUE THREAD

**Issue by 0xdf0xdf** [guard/listen#528]
I've got a CI/CD pipeline that runs on the docker image ruby:latest. I started getting this error today:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching https://github.com/jekyll/jekyll.git
listen-3.2.1 requires ruby version >= 2.2.7, ~> 2.2, which is incompatible with
the current version, ruby 3.0.0p0
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

It says it needs version greater than 2.2, but for some reason it doesn't think 3.0 is?

**Comment by ColinDKelley** [comment]
Yes, that's because `'~> 2.2'` is the Sem-Ver notation that is equivalent to `'>= 2.2', '< 3'`. (The Sem-Ver convention is that major version number changes are breaking. But Ruby has never really followed Sem-Ver.)

This is fixed in newer versions of `listen` where it now is simply `''>= 2.2.7`.
