### ISSUE TITLE
Listen doesn't install in Ruby 3.0

### ISSUE THREAD

**Issue by mbaudis** [guard/listen#534]
The listen installation (required by Jekyll) errors under Ruby 3.0:
```
> bundle install             
Fetching gem metadata from https://rubygems.org/.........
listen-3.2.1 requires ruby version >= 2.2.7, ~> 2.2, which is
incompatible with the current version, ruby 3.0.0p0
> gem install listen -v 3.1.5
ERROR:  Error installing listen:
	listen-3.1.5 requires Ruby version ~> 2.2, >= 2.2.3. The current ruby version is 3.0.0.0.
```

##### Environment:

* Mac OS X 11.3 Beta
* ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

**Comment by ColinDKelley** [comment]
This looked like a duplicate of https://github.com/guard/listen/issues/489

That was fixed in https://github.com/guard/listen/releases/tag/v3.3.0

Ok if I close this ticket as a duplicate?

**Comment by ColinDKelley** [comment]
^ @mbaudis ?

**Comment by mbaudis** [comment]
@ColinDKelley Thanks - not sure why this was then getting an older version? Works now...
