### ISSUE TITLE
Ignore emacs editor temp file.

### ISSUE THREAD

**Issue by zw963** [guard/listen#543]
Emacs will generate some temp files before save, e.g. `.#app.rb`, `#app.rb#`.

So, i thought we should add those rarely used filename to ignore list. like this:

```rb
listener.ignore /\A\.?#/
```

**Comment by ColinDKelley** [comment]
@zw963 That regexp looks a bit more general than the two patterns, because it would also match `#app.rb`.

Does this pattern look accurate to match exactly those 2 cases? `/\A.#|\A#.*#\z/`?

Could you please make a PR with this change, along with specs?

**Comment by zw963** [comment]
> That regexp looks a bit more general than the 2 examples you show

Yes,  `/\A\.?#/` is a little general (though, this is my original purpose)

I just want ignore any file which prefix with `.#` or `#`, if you favor more accurate, i can exact file name like `(?:^\.#|^#.+#)`, will create PR later.

**Comment by zw963** [comment]
@ColinDKelley  PR, #546 , thank you.
