### ISSUE TITLE
Automatic file reloading stopped working 

### ISSUE THREAD

**Issue by asfarley** [guard/listen#559]
I am using Rails 6.02, ruby 2.6.1, listen 3.1.5, spring-watcher-listen 2.0.1 under Ubuntu 18.04 in a VMWare Workstation virtual machine on a Windows 10 host. 

In the past, I have been using RubyMine and as far as I remember, automatic source code reloading was working in development mode. 

Now, it seems that automatic source-code reloading is not happening by default in development mode; I had to comment out this config line to get it working:

`config.file_watcher = ActiveSupport::EventedFileUpdateChecker`

I see a bunch of other reports of this issue happening under Docker, or under symlinked folders in Capistrano, or even when running directly under Windows. However, I do not see any reports of this issue occurring on Ubuntu in a VM. 

Is this expected? I wish I knew what change caused this because I thought it was working recently.

**Comment by asfarley** [comment]
Also, I am developing within RubyMine and my environment uses rbenv.

**Comment by LouisaNikita** [comment]
我已收到你的邮件，谢谢！

**Comment by asfarley** [comment]
This turned out to be related to previously reported issues where the amount of inotify watches was used up by a large amount of files in node_modules; using listener.ignore as suggested inside config/spring.rb fixed the issue.
